Iter13
darod1n/urlshorten pull request #9
Opened 2023-06-13 21:00 UTC by darod1n

2023-06-17 17:26 UTC, s-shpak requested changes

2023-06-17 17:26 UTC, s-shpak commented on cmd/shortener/main.go
> +	db, err := storage.NewDB(serverConfig.Path, serverConfig.DriverName, serverConfig.DataSourceName)
А что если надо будет создать хранилище не в БД, а в памяти?

2023-06-17 17:26 UTC, s-shpak commented on cmd/shortener/main.go
> +		ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
У тебя есть контекст в `r`, лучше использовать его

2023-06-17 17:26 UTC, s-shpak commented on internal/config/config.go
> +	config.DriverName = "pgx"
Зачем, если это константа? Спрячь это значение в пакете `postgresql`, т.к. пользователю пакета необязательно знать, какой драйвер используется

2023-06-17 17:26 UTC, s-shpak commented on internal/handlers/handlers.go
> +	log.Println(bodyBatch)
deadcode

2023-06-17 17:26 UTC, s-shpak commented on internal/storage/file/storage.go
> +		shortURL, _ := db.AddURL(ctx, val.OriginURL)
Ошибки надо проверять и обрабатывать

2023-06-17 17:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +		row := db.base.QueryRowContext(ctx, "select short_url from urls where original_url=$1;", url)
А зачем этот запрос, если ты уже используешь `returning`?

2023-06-17 17:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +	for _, val := range batch {
Сейчас это не батчинг, это запись данных в БД по очереди. В идеале, ты должен делать фиксированное количество запросов к БД (один, например), которое не должно зависеть от количества отправляемых данных. Для батчинга можно:
1. перейти на `pgx` вместо `db/sql`
2. формировать запрос самому
3. использовать библиотеку типа `sqlx` или `squirrel`

2023-06-17 17:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +	Create or replace function random_string() returns text as
Не надо помещать эту логику в БД (но круто, что ты попробовал писать на `pl/pgsql`)

2023-06-17 17:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +		return nil, err
Ошибки лучше оборачивать

2023-06-19 16:15 UTC, darod1n commented on internal/storage/postgresql/storage.go
> +		row := db.base.QueryRowContext(ctx, "select short_url from urls where original_url=$1;", url)
@s-shpak `returning`  ничего не возвращает в случае ошибки(когда original_url в бд уже существует). Поэтому если нам ничего не вернул запрос надо запросить short_url у которого есть такой original_url

2023-06-20 13:13 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +		row := db.base.QueryRowContext(ctx, "select short_url from urls where original_url=$1;", url)
Ты прав. В таком случае, чтобы избежать двух запросов, я бы исползовал CTE, можешь посмотреть пример здесь: https://dev.to/yugabyte/insert-on-conflict-returning-old-values-5025 (там довольно сложная логика, можно сделать один дополнительный запрос, это не сильно повлияет на производительность сейчас)

2023-06-20 13:26 UTC, s-shpak requested changes

2023-06-20 13:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +		valueQuery := fmt.Sprintf("('%s', '%s')", val.OriginURL, shortURL)
Намного лучше, но теперь возможна SQL-инъекция. Подумай, как составить запрос так, чтобы он был похож на 

```go
ExecContext(`INSERT INTO urls (original_url, short_url) VALUES ($1, $2)`, url, shortURL)
```

2023-06-20 13:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +func (db *DB) Close() error {
При завершении программы соединение надо закрыть

2023-06-20 13:26 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +func (db *DB) AddURL(ctx context.Context, url string) (string, error) {
Если ты делаешь в функции несколько SQL-запросов, то их надо оборачивать в транзакцию

2023-06-20 15:10 UTC, darod1n commented on internal/storage/postgresql/storage.go
> +		row := db.base.QueryRowContext(ctx, "select short_url from urls where original_url=$1;", url)
Я уже думал об этом решение поэтому реализую его

2023-06-21 12:51 UTC, s-shpak requested changes

2023-06-21 12:51 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +	b := db.base.SendBatch(ctx, batch)
Т.к. это несоклько запросов, их надо обернуть в транзакцию

2023-06-22 21:25 UTC, s-shpak requested changes

2023-06-22 21:25 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +	defer func() {
`defer tx.Commit()` следует поместить после создания танзакции (на строке 82): если до вызова коммита ты вызовешь `tx.Rollback`, то `Commit` просто не сделает ничего.

Rollback надо вызывать в случае люой ошибки (а не только при проверке реузльтата `b.Close`)

2023-06-22 21:25 UTC, s-shpak commented on internal/storage/postgresql/storage.go
> +			_ = tx.Rollback(ctx)
Ошибку надо проверить и залогировать, если она произошла

2023-06-23 08:45 UTC, s-shpak approved these changes

2023-06-23 10:56 UTC, merged